### ISSUE TITLE
Prevent to unmount steps from DOM

### ISSUE THREAD

**Issue by noashka** [americanexpress/react-albus#23]
Hello! How I can prevent unmounting child elements? 
When I use simple CSSTransition  without react-albus, I set prop 'unmountOnExit' to false. Component stays mounted after it reaches the 'exited' state

**Comment by nathanforce** [comment]
Hey thanks for reaching out.

Could you prepare an example on CodeSandbox showing your issue and we can try and work through it?

**Comment by noashka** [comment]
Sure. I'll prepare for you example. But a bit later.
Thank you for quick response!

**Comment by noashka** [comment]
Can you look for examples, please ?

**Comment by nathanforce** [comment]
Ok.  This component wasn't really designed to be used in that way.  Wizard assumes that you will be rendering one step at a time and unmounting steps when they are inactive.

That being said, because of the flexibility provided by the `render` prop on `Wizard`, I was able to get an example that seems to be the groundwork for what you're asking.

https://codesandbox.io/s/l7pxonzyml

You can play with that idea and try to add your transitions if you'd like, but I feel that react-albus may not be suited for your use case.

Thanks!

**Comment by noashka** [comment]
Ok. Thank you for feedback! I'll think about your example.
