### ISSUE TITLE
How to start a wizard on a given step?

### ISSUE THREAD

**Issue by puopg** [americanexpress/react-albus#24]
The best way i figure I could do something like this is to call ```push``` to move to a given step with the id? But Im not really sure where to perform that operation since if my component is the Wizard component, where do I get access to the push method? Since withWizard only would apply to components inside the Wizard tree.

**Comment by nathanforce** [comment]
Hey great question! Maybe our docs could be a bit more explicit here. 

You’ll want to use the onNext function, which will be called once on initialization. You can use the wizard state and helper functions provided to set your first step. 

Let me know if you need some more help and I can whip up an example.

**Comment by puopg** [comment]
Right so I tried that, and it does set the step as such, but then I cant call previous and move back to the previous step. Likewise, unless perhaps I use an external flag, moving to the next step also triggers onNext to fire. 
```
public onNext = (wizard) => {
    wizard.push('Confirm');
  }
```

```
 <Wizard onNext={this.onNext}>
        <WizardHeader/>

        <Steps>
          <Step id="Review">
            {({ next }) => (
              <div>
                <div>Review</div>
              </div>
            )}
          </Step>

          <Step id="Confirm">
            {({ next, previous }) => (
              <div>
                <div>Confirm</div>
              </div>
            )}
          </Step>
  
          <Step id="Confirm2">
            {({ previous }) => (
              <div>
                <div>Confirm 2</div>
              </div>
            )}
          </Step>
        </Steps>
      </Wizard>
```

**Comment by nathanforce** [comment]
I see.  So the `previous` function that is provided by `<Step />` actually uses the history stack of your Wizard, rather than the linear flow of your steps.  We decided to do this because we have no way of knowing whether your flow is linear.  So its more like 'go back to the step I was on before' than 'go to the step before this one in the list'.  

The good news is that you can totally create this experience on your own using a combination of `steps`, `step`, and `push`.  Whether you want to do this in `onNext` or directly in your render is up to you.

```
const { steps, step, push } = wizard;
const goToPreviousLinearStep = () => {
   push(steps.findIndex(({ id }) => id === step.id) - 1)
}
```

**Comment by puopg** [comment]
Ah ok I see. Thanks!
